name: Dapper CI on PR and Merge
run-name: CI on Merge to ${{ github.ref_name }}

on:
  pull_request:
  push:
    branches:
      - release/v0.16

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: martinsvitols268/dapper:0.6.1
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build with Dapper
        run: dapper ci
