name: Dapper CI on PR and Merge
run-name: CI on Merge to ${{ github.ref_name }}

on:
  pull_request:
  push:
    branches:
      - release/v0.16

jobs:
  validate:
    runs-on: ubuntu-latest
    container:    
      image: golang:latest
    steps:
      - name: Get dapper
        run: |
          wget https://github.com/rancher/dapper/releases/download/v0.6.0/dapper-Linux-x86_64
          chmod +x dapper-Linux-x86_64
          mv dapper-Linux-x86_64 /usr/local/bin/dapper
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: build with Dapper
        run: dapper ci
